### ISSUE TITLE
Transmute setup does not work correctly

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-cli#4]
Does not instantiate `.transmute` folder in user home directory on global install

**Comment by OR13** [comment]
I broke this at some point... it works correctly in `0.1.36`...

As a new user, 

first install the cli globally, then: 

`transmute setup` or `transmute setup --from ~/Code/secrets/.transmute/` if you have a backed up .transmute folder somewhere.

Make sure the keys in .transmute are correct and not just empty stubs before proceeding...
